"""update user_login identifier to unique

Revision ID: f355d253b4d4
Revises: 9b084d822a36
Create Date: 2026-04-03 11:28:19.035622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f355d253b4d4'
down_revision: Union[str, Sequence[str], None] = '9b084d822a36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_logins', ['identifier'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_logins', type_='unique')
    # ### end Alembic commands ###
